language: node_js
dist: trusty
node_js:
- '11'
sudo: required
env:
  SONAR_API_KEY=jTNnV4u+zjYXbtCdGOQ8ufaAeujJPCsgjbPPK235OGFz0+v6FmmZW1ZZIZhwf50MNt3vjwK7i5eUohY4ROQNFUuuH/ECrmtnRZP2EraB1wAnEuuowoHeica4NR5GDA0FB4Se+6fkCguTQHR8RSwNNxQTZQQW92DYM3TV08M+1cUHeP5pHAhWFB+eFLagfsx7VG7UkayF3mv78LIrJTO7GSGItuCjTHauxSkuQ0e2TxKK8VUxMeQxUFG1uw99f80LfQ4IsF6D717T2dMRnRo/AympLa8WSLgK8/2SaeeitTyrvdyWmS7SkcB/gGjYYmupHY8BN0SdpyB5S7dSQf0lWnukW48QyqtwBlxzRv8YrYE2O+kbdBfzX4FMmu9bmsMNfnl0pzYdT2aRaJaxXfBojCEL+HU44FH3kaxW1O1mhvJMQvv9tabWq+ghnuVksD0tbcYkP5efkVcSNnCncg5zHPed4L36vF5dYv2V2BnQDZS8SQnSncaMYiK4B2sWRJ82LmYQjWEnk71O0C4BDacD9ByQ1h9clSbcCUlVVEFYBP94y3PczhqmnPR+jY2DKFdA8sHY6sFeFXlrbi9d1hJYjGWtFPqWwjqt+QOjDpKCgYvklR/9zOIRLLus8+79+xwGHBPARx7oa4HoAslRKdcob3ltTYDiZ1UiLUpCNG5WNhE=

ddons:
  sonarcloud:
    organization: "visiativ"
    token:
      secure: $SONAR_API_KEY

before_script:
- npm install -g @angular/cli


script:
  - sonar-scanner