language: node_js
dist: trusty
node_js:
  - '11'
sudo: required

env:
  global:
    secure: vI5Pcdh82eRU8gRWXrsTh5dJgwc1tTnaTxtwp5oulCIqJnLac0Z2hsioWJCYRxnGIvoOwX5h0c2eYkm8PZDt9E8WcTeGuRiyvVXMRzF0DBzMp711hLTxdeK7W2+C8L3yRIConpgYF76Ndf2Jq8GBFhuJtWtwh/b1qSyil9YheZP8imp3+Ng4ueIMq2g24AKVTZk9MqUOdDVCS1o+CXHT258lJAY4OkO85b1bEZwZYq4AE8cj4urtDXA+UUmNVGlGkkV91DctOF5MZCiu8RhdvglYPfMmU9/mxInVIsiMMXnCRXYZVLSMsoh4085/MlVpghH5C3t/wL8rEnDceOJx4j+gfB7eULDtK21u11IUWCjdMEH28Y0jpfj50zSkDwUdopQt/jI4jgJoKwdjDcaVgpcNXe/jygUcJbP+2PAYU+ykwVN8mh/9/Usynx4TPkToXQFaSf6d5MIlLjpgL/Er0eGsZocyMIaKzmpHAft0Mh9xUBaWe7C6CrOY976jIrmOFOSd889dA838xFuEkYYuGdgxLcBUIXHTY9sMDFtZ+2J88AqwbBBrRI8M7kH8CJpCQ5vPFcmnNLh5fM1qiDnxcY6Ej13aYdu/pQrG1/PW8LKpN7RRtuUlCwDgEAYh2h+QqEHs+oWsKVZpyNiH+PMRYduU+TF8sHobpjgS8L90UzE=
  - SONAR_API_KEY=SxxHzwT5RCJKtsTdsthmoHy3/bjMt2N94lXkjXBSawcM/IM50OzmwcsMz547ibZOP9lyyERTAWC6TNyudr/G//tOkRv0qGyUTSsj9twcxKPXsNtrCib+85dClz1KBD0kzB7MVAL6fqLth2TEtr4rlw9s4v4dGYlsK3JbdR1fIfgRUzUTu08x4GAymZWx26bPwSr0MpzKrfMydfnWW6D8IzO8VBk9MIFxT6qjmXb0J4k/Jwhuv9Eak3pn9xKhJxEMb1qNgIwElC5sZOV+DNv5VsnAOcOAMlruBEQ2ktLXCI18ch/MQSU8GXaKFAy+p3zL0bh856Oj/G26xgfzh+Z+frUZghxp2zxhupMkZKRQcfQnGuy5BVIlLjorA8fECLoCtiIaZNCNcoFU5iwLNCYQgotx3B0G0TnnuW/KNlDcaCX5ByRJuH/+ATEjSqIMujihAhJsnfc3EhyakKwGdnZJAqp3bIY+BtlMM0vH1I+cdeZ7JqCyO7tBKUC2YCBP2c0TGH96MI6kYWwU9ckVgV0eQm+l6WtWHjJk2Swka2Loh6fBSIHINTfIUFVSvWZGiKtA7m5QKhNj+luscuB0qmQy8xbpv/jjEHJABU1Onz/AZqT1FOvkPIlOvrG6g452zT8xVnuiAhWL+5q8EXMhhWCyB3iR8MFLrL6zpeVYf0UjuC4=
addons:
  sonarcloud:
    organization: visiativ
    token:
      secure: $SONAR_API_KEY

before_script:
  - npm install -g @angular/cli

script:
  - ng build --prod
  - sonar-scanner -Dsonar.login=$SONAR_API_KEY
